-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema DRUPADI_V1
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `DRUPADI_V1` ;

-- -----------------------------------------------------
-- Schema DRUPADI_V1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DRUPADI_V1` DEFAULT CHARACTER SET latin1 ;
USE `DRUPADI_V1` ;

-- -----------------------------------------------------
-- Table `DRUPADI_V1`.`ACTIONPLAN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DRUPADI_V1`.`ACTIONPLAN` ;

CREATE TABLE IF NOT EXISTS `DRUPADI_V1`.`ACTIONPLAN` (
  `ACTIONPLANID` INT(11) NOT NULL,
  `ACTION` VARCHAR(45) NOT NULL COMMENT 'Pupuk K \nAir\nPestisida\netc',
  `VALUE` FLOAT NOT NULL COMMENT '10 liter\n2 kg\netc\n-- have to connect to SOM',
  `CREATEDBY` VARCHAR(45) NOT NULL,
  `DTCREATED` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ACTIONPLANID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `DRUPADI_V1`.`ACTION_UOM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DRUPADI_V1`.`ACTION_UOM` ;

CREATE TABLE IF NOT EXISTS `DRUPADI_V1`.`ACTION_UOM` (
  `ACTIONID` INT(11) NOT NULL,
  `UOMID` INT(11) NOT NULL,
  PRIMARY KEY (`ACTIONID`, `UOMID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `DRUPADI_V1`.`AREA_LOCATION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DRUPADI_V1`.`AREA_LOCATION` ;

CREATE TABLE IF NOT EXISTS `DRUPADI_V1`.`AREA_LOCATION` (
  `AREAID` INT(11) NOT NULL,
  `LATITUDE` FLOAT NOT NULL,
  `LONGITUDE` FLOAT NOT NULL,
  PRIMARY KEY (`AREAID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `DRUPADI_V1`.`AREA_ACTIONPLAN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DRUPADI_V1`.`AREA_ACTIONPLAN` ;

CREATE TABLE IF NOT EXISTS `DRUPADI_V1`.`AREA_ACTIONPLAN` (
  `AREAID` INT(11) NOT NULL,
  `ACTIONPLANID` INT(11) NOT NULL,
  PRIMARY KEY (`AREAID`, `ACTIONPLANID`),
  INDEX `fk_AREA_ACTIONPLAN_1_idx` (`ACTIONPLANID` ASC),
  CONSTRAINT `fk_AREA_ACTIONPLAN_1`
    FOREIGN KEY (`ACTIONPLANID`)
    REFERENCES `DRUPADI_V1`.`ACTIONPLAN` (`ACTIONPLANID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AREA_ACTIONPLAN_2`
    FOREIGN KEY (`AREAID`)
    REFERENCES `DRUPADI_V1`.`AREA_LOCATION` (`AREAID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `DRUPADI_V1`.`INFORMATION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DRUPADI_V1`.`INFORMATION` ;

CREATE TABLE IF NOT EXISTS `DRUPADI_V1`.`INFORMATION` (
  `INFORMATIONID` INT(11) NOT NULL,
  `SUBJECT` VARCHAR(60) NOT NULL,
  `CONTENT` VARCHAR(100) NOT NULL,
  `CREATEDBY` VARCHAR(45) NOT NULL,
  `DTCREATED` DATETIME NOT NULL,
  PRIMARY KEY (`INFORMATIONID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `DRUPADI_V1`.`AREA_INFORMATION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DRUPADI_V1`.`AREA_INFORMATION` ;

CREATE TABLE IF NOT EXISTS `DRUPADI_V1`.`AREA_INFORMATION` (
  `AREAID` INT(11) NOT NULL,
  `INFORMATIONID` INT(11) NOT NULL,
  PRIMARY KEY (`AREAID`, `INFORMATIONID`),
  INDEX `fk_AREA_INFORMATION_1_idx` (`INFORMATIONID` ASC),
  CONSTRAINT `fk_AREA_INFORMATION_1`
    FOREIGN KEY (`INFORMATIONID`)
    REFERENCES `DRUPADI_V1`.`INFORMATION` (`INFORMATIONID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AREA_INFORMATION_2`
    FOREIGN KEY (`AREAID`)
    REFERENCES `DRUPADI_V1`.`AREA_LOCATION` (`AREAID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `DRUPADI_V1`.`RF_ORGANIZATION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DRUPADI_V1`.`RF_ORGANIZATION` ;

CREATE TABLE IF NOT EXISTS `DRUPADI_V1`.`RF_ORGANIZATION` (
  `ORGANIZATIONID` INT(11) NOT NULL,
  `ORGANIZATIONNAME` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ORGANIZATIONID`, `ORGANIZATIONNAME`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `DRUPADI_V1`.`RF_CONTACTTYPE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DRUPADI_V1`.`RF_CONTACTTYPE` ;

CREATE TABLE IF NOT EXISTS `DRUPADI_V1`.`RF_CONTACTTYPE` (
  `CONTACTTYPEID` INT(11) NOT NULL,
  `CONTACTTYPE` VARCHAR(45) NOT NULL COMMENT '1 = MOBILE NUMBER\n2 = HOME PHONE\n3 = WORK PHONE\n4 = HOME ADDRESS\n5 = ETC\n30 = BANK DETAILS\n31 = BANK NAME\n32 = BANK ACCOUNT\n33 = BANK ADDRESS\nETC',
  PRIMARY KEY (`CONTACTTYPEID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `DRUPADI_V1`.`ORGANIZATION_CONTACT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DRUPADI_V1`.`ORGANIZATION_CONTACT` ;

CREATE TABLE IF NOT EXISTS `DRUPADI_V1`.`ORGANIZATION_CONTACT` (
  `ORGANIZATIONID` INT(11) NOT NULL,
  `CONTACTTYPE` INT(11) NOT NULL,
  `CONTACTVALUE` VARCHAR(200) NULL DEFAULT NULL,
  `DTSTART` DATE NOT NULL,
  PRIMARY KEY (`ORGANIZATIONID`, `CONTACTTYPE`, `DTSTART`),
  INDEX `fk_ORGANIZATION_CONTACT_2_idx` (`CONTACTTYPE` ASC),
  CONSTRAINT `fk_ORGANIZATION_CONTACT_1`
    FOREIGN KEY (`ORGANIZATIONID`)
    REFERENCES `DRUPADI_V1`.`RF_ORGANIZATION` (`ORGANIZATIONID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ORGANIZATION_CONTACT_2`
    FOREIGN KEY (`CONTACTTYPE`)
    REFERENCES `DRUPADI_V1`.`RF_CONTACTTYPE` (`CONTACTTYPEID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `DRUPADI_V1`.`RF_USER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DRUPADI_V1`.`RF_USER` ;

CREATE TABLE IF NOT EXISTS `DRUPADI_V1`.`RF_USER` (
  `USERID` INT(11) NOT NULL,
  `USERNAME` VARCHAR(60) NOT NULL,
  `PASSWORD` VARCHAR(12) NOT NULL,
  `FIRSTNAME` VARCHAR(60) NOT NULL,
  `LASTNAME` VARCHAR(60) NOT NULL,
  `DTCREATED` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`USERID`, `USERNAME`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `DRUPADI_V1`.`ORGANIZATION_USER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DRUPADI_V1`.`ORGANIZATION_USER` ;

CREATE TABLE IF NOT EXISTS `DRUPADI_V1`.`ORGANIZATION_USER` (
  `ORGANIZATIONID` INT(11) NOT NULL,
  `USERID` INT(11) NOT NULL,
  `DTSTART` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ORGANIZATIONID`, `USERID`),
  INDEX `fk_ORGANIZATION_USER_2_idx` (`USERID` ASC),
  CONSTRAINT `fk_ORGANIZATION_USER_1`
    FOREIGN KEY (`ORGANIZATIONID`)
    REFERENCES `DRUPADI_V1`.`RF_ORGANIZATION` (`ORGANIZATIONID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ORGANIZATION_USER_2`
    FOREIGN KEY (`USERID`)
    REFERENCES `DRUPADI_V1`.`RF_USER` (`USERID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `DRUPADI_V1`.`RF_PROJECT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DRUPADI_V1`.`RF_PROJECT` ;

CREATE TABLE IF NOT EXISTS `DRUPADI_V1`.`RF_PROJECT` (
  `PROJECTID` INT(11) NOT NULL,
  `PROJECT` VARCHAR(200) NOT NULL,
  `DESCRIPTION` VARCHAR(200) NULL DEFAULT NULL,
  `DTSTART` DATE NOT NULL,
  `DTEND` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`PROJECTID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `DRUPADI_V1`.`PROJECT_AREA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DRUPADI_V1`.`PROJECT_AREA` ;

CREATE TABLE IF NOT EXISTS `DRUPADI_V1`.`PROJECT_AREA` (
  `PROJECTID` INT(11) NOT NULL,
  `AREAID` INT(11) NOT NULL,
  `DTSTART` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`PROJECTID`, `AREAID`),
  INDEX `fk_PROJECT_AREA_1_idx` (`AREAID` ASC),
  CONSTRAINT `fk_PROJECT_AREA_1`
    FOREIGN KEY (`AREAID`)
    REFERENCES `DRUPADI_V1`.`AREA_LOCATION` (`AREAID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PROJECT_AREA_2`
    FOREIGN KEY (`PROJECTID`)
    REFERENCES `DRUPADI_V1`.`RF_PROJECT` (`PROJECTID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `DRUPADI_V1`.`RF_ROLE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DRUPADI_V1`.`RF_ROLE` ;

CREATE TABLE IF NOT EXISTS `DRUPADI_V1`.`RF_ROLE` (
  `ROLEID` INT(11) NOT NULL,
  `ROLE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ROLEID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `DRUPADI_V1`.`RF_SOM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DRUPADI_V1`.`RF_SOM` ;

CREATE TABLE IF NOT EXISTS `DRUPADI_V1`.`RF_SOM` (
  `SOMID` INT(11) NOT NULL,
  `SOM` VARCHAR(60) NOT NULL COMMENT 'Metric\nImperial',
  PRIMARY KEY (`SOMID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `DRUPADI_V1`.`RF_UOM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DRUPADI_V1`.`RF_UOM` ;

CREATE TABLE IF NOT EXISTS `DRUPADI_V1`.`RF_UOM` (
  `UOMID` INT(11) NULL DEFAULT NULL,
  `SOMID` INT(11) NOT NULL,
  `MEASUREMENT` VARCHAR(60) NOT NULL COMMENT 'Height = cm\nDistance = m\nMass = kg\netc',
  `UOM` VARCHAR(10) NOT NULL COMMENT 'Distance = m\nLength = cm\nMass = kg\netc',
  PRIMARY KEY (`SOMID`),
  CONSTRAINT `fk_RF_UOM_1`
    FOREIGN KEY (`SOMID`)
    REFERENCES `DRUPADI_V1`.`RF_SOM` (`SOMID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `DRUPADI_V1`.`USER_CONTACT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DRUPADI_V1`.`USER_CONTACT` ;

CREATE TABLE IF NOT EXISTS `DRUPADI_V1`.`USER_CONTACT` (
  `USERID` INT(11) NOT NULL,
  `CONTACTTYPEID` INT(11) NOT NULL,
  `CONTACTVALUE` VARCHAR(200) NOT NULL,
  `DTSTART` DATE NOT NULL,
  PRIMARY KEY (`USERID`, `CONTACTTYPEID`, `DTSTART`),
  INDEX `fk_USER_CONTACT_2_idx` (`CONTACTTYPEID` ASC),
  CONSTRAINT `fk_USER_CONTACT_1`
    FOREIGN KEY (`USERID`)
    REFERENCES `DRUPADI_V1`.`RF_USER` (`USERID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USER_CONTACT_2`
    FOREIGN KEY (`CONTACTTYPEID`)
    REFERENCES `DRUPADI_V1`.`RF_CONTACTTYPE` (`CONTACTTYPEID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `DRUPADI_V1`.`USER_ROLE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DRUPADI_V1`.`USER_ROLE` ;

CREATE TABLE IF NOT EXISTS `DRUPADI_V1`.`USER_ROLE` (
  `USERID` INT(11) NOT NULL,
  `ROLEID` INT(11) NOT NULL,
  PRIMARY KEY (`USERID`, `ROLEID`),
  INDEX `fk_USER_ROLE_2_idx` (`ROLEID` ASC),
  CONSTRAINT `fk_USER_ROLE_1`
    FOREIGN KEY (`USERID`)
    REFERENCES `DRUPADI_V1`.`RF_USER` (`USERID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USER_ROLE_2`
    FOREIGN KEY (`ROLEID`)
    REFERENCES `DRUPADI_V1`.`RF_ROLE` (`ROLEID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `DRUPADI_V1`.`USER_SETTINGS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DRUPADI_V1`.`USER_SETTINGS` ;

CREATE TABLE IF NOT EXISTS `DRUPADI_V1`.`USER_SETTINGS` (
  `USERID` INT(11) NOT NULL,
  `SOMID` INT(11) NOT NULL,
  `DTSTART` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`USERID`, `SOMID`, `DTSTART`),
  INDEX `fk_USER_SETTINGS_2_idx` (`SOMID` ASC),
  CONSTRAINT `fk_USER_SETTINGS_1`
    FOREIGN KEY (`USERID`)
    REFERENCES `DRUPADI_V1`.`RF_USER` (`USERID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USER_SETTINGS_2`
    FOREIGN KEY (`SOMID`)
    REFERENCES `DRUPADI_V1`.`RF_SOM` (`SOMID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
